### ISSUE TITLE
Reloading cells at index path will cause crash

### ISSUE THREAD

**Issue by farshadtx** [strawberrycode/SCSectionBackground#1]
HI,

I got block by this issue. if you simply add a reload line to in didSelectItemAt and then run the project. by scrolling to the bottom and getting back to the top. if you tap on mid-cells app will crash.

here is the error:
`*** Assertion failure in -[UICollectionViewData layoutAttributesForDecorationViewOfKind:atIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UICollectionViewData.m:982
2017-02-09 16:18:44.200 SCSectionBackground[25643:420562] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'no UICollectionViewLayoutAttributes instance for -layoutAttributesForDecorationViewOfKindOfKind: sectionBackground at path <NSIndexPath: 0xc000000000c00316> {length = 2, path = 3 - 6}'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112e28d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010fb1421e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112e2ce42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010f6a966d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   UIKit                               0x000000011109dbeb -[UICollectionViewData layoutAttributesForDecorationViewOfKind:atIndexPath:] + 1045
	5   UIKit                               0x000000011109adea -[UICollectionViewData rectForDecorationElementOfKind:atIndexPath:] + 344
	6   UIKit                               0x0000000111052735 -[UICollectionView _viewAnimationsForCurrentUpdate] + 11507
	7   UIKit                               0x0000000111056899 __71-[UICollectionView _updateWithItems:tentativelyForReordering:animator:]_block_invoke.1993 + 197
	8   UIKit                               0x00000001107b0239 +[UIView(Animation) performWithoutAnimation:] + 90
	9   UIKit                               0x00000001110553ef -[UICollectionView _updateWithItems:tentativelyForReordering:animator:] + 3942
	10  UIKit                               0x000000011104f421 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 17765
	11  UIKit                               0x000000011104ace1 -[UICollectionView _updateRowsAtIndexPaths:updateAction:] + 377
	12  SCSectionBackground                 0x000000010f51cab0 _TFFC19SCSectionBackground41SectionBackgroundCollectionViewControllerP33_342C3AFA0BE40941A52813FC0FF474EC10reloadCellFT9indexPathV10Foundation9IndexPath_T_U_FT_T_ + 240
	13  SCSectionBackground                 0x000000010f51cb27 _TTRXFo___XFdCb___ + 39
	14  UIKit                               0x00000001107b0239 +[UIView(Animation) performWithoutAnimation:] + 90
	15  SCSectionBackground                 0x000000010f51c993 _TFC19SCSectionBackground41SectionBackgroundCollectionViewControllerP33_342C3AFA0BE40941A52813FC0FF474EC10reloadCellfT9indexPathV10Foundation9IndexPath_T_ + 259
	16  SCSectionBackground                 0x000000010f51c7f9 _TFC19SCSectionBackground41SectionBackgroundCollectionViewController14collectionViewfTCSo16UICollectionView15didSelectItemAtV10Foundation9IndexPath_T_ + 57
	17  SCSectionBackground                 0x000000010f51c877 _TToFC19SCSectionBackground41SectionBackgroundCollectionViewController14collectionViewfTCSo16UICollectionView15didSelectItemAtV10Foundation9IndexPath_T_ + 87
	18  UIKit                               0x000000011102f6e4 -[UICollectionView _selectItemAtIndexPath:animated:scrollPosition:notifyDelegate:] + 702
	19  UIKit                               0x000000011105a4d2 -[UICollectionView touchesEnded:withEvent:] + 649
	20  UIKit                               0x000000011090df6b forwardTouchMethod + 348
	21  UIKit                               0x000000011090e034 -[UIResponder touchesEnded:withEvent:] + 49
	22  UIKit                               0x000000011090df6b forwardTouchMethod + 348
	23  UIKit                               0x000000011090e034 -[UIResponder touchesEnded:withEvent:] + 49
	24  UIKit                               0x0000000110766545 -[UIWindow _sendTouchesForEvent:] + 2747
	25  UIKit                               0x0000000110767c33 -[UIWindow sendEvent:] + 4011
	26  UIKit                               0x00000001107149ab -[UIApplication sendEvent:] + 371
	27  UIKit                               0x0000000110f0172d __dispatchPreprocessedEventFromEventQueue + 3248
	28  UIKit                               0x0000000110efa463 __handleEventQueue + 4879
	29  CoreFoundation                      0x0000000112dcd761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	30  CoreFoundation                      0x0000000112db298c __CFRunLoopDoSources0 + 556
	31  CoreFoundation                      0x0000000112db1e76 __CFRunLoopRun + 918
	32  CoreFoundation                      0x0000000112db1884 CFRunLoopRunSpecific + 420
	33  GraphicsServices                    0x0000000115c96a6f GSEventRunModal + 161
	34  UIKit                               0x00000001106f6c68 UIApplicationMain + 159
	35  SCSectionBackground                 0x000000010f51dd2f main + 111
	36  libdyld.dylib                       0x0000000113dd868d start + 1
	37  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by abhishekbanerjee-meesho** [comment]
@farshadtx
Hi, Was this resolved for you? I am also getting this crash.

**Comment by farshadtx** [comment]
Ended up not using this after the crash.
